### ISSUE TITLE
TypeError thrown instead of InvalidAuth

### ISSUE THREAD

**Issue by tkdrob** [ludeeus/pytautulli#18]
### Checklist

- [X] I'm running the newest version <https://github.com/ludeeus/pytautulli/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

When ever an invalid authentication key is provided, a TypeError occurs during my construction of a config flow. A check of `self.sessions` in `activity.py` seems to resolve the issue.

### Logs

```text
2021-10-10 03:58:52 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Tautulli for tautulli
Traceback (most recent call last):
  File "/Users/tkdrob/core/venv/lib/python3.9/site-packages/pytautulli/decorator.py", line 54, in wrapper
    response = PyTautulliApiResponse(
  File "/Users/tkdrob/core/venv/lib/python3.9/site-packages/pytautulli/models/base.py", line 44, in __init__
    value = self.__getattribute__(f"_generate_{key}")(value)
  File "/Users/tkdrob/core/venv/lib/python3.9/site-packages/pytautulli/models/response.py", line 39, in _generate_data
    return self._datatype(data, self._datatype)
  File "/Users/tkdrob/core/venv/lib/python3.9/site-packages/pytautulli/models/base.py", line 47, in __init__
    self.__post_init__()
  File "/Users/tkdrob/core/venv/lib/python3.9/site-packages/pytautulli/models/activity.py", line 22, in __post_init__
    self.sessions = [PyTautulliApiSession(session) for session in self.sessions]
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tkdrob/core/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/Users/tkdrob/core/homeassistant/components/tautulli/__init__.py", line 54, in async_setup_entry
    await api_client.async_get_activity()
  File "/Users/tkdrob/core/venv/lib/python3.9/site-packages/pytautulli/decorator.py", line 105, in wrapper
    raise PyTautulliException(client, exception) from exception
pytautulli.exceptions.PyTautulliException: 'NoneType' object is not iterable
```

**Comment by tkdrob** [comment]
Here is my current testing branch: https://github.com/tkdrob/core/tree/tautulli_configflow

**Comment by ludeeus** [comment]
Fixed in https://github.com/ludeeus/pytautulli/pull/14
